### Configuration Variables
@keycloak-realm = recipes-sharing-platform
@keycloak-url = http://localhost:9090
@client-id = recipes-sharing-platform-app
@test-username1 = test.user@gmail.com
@test-username2 = test.user2@gmail.com
@test-password = password
@client-secret = 2gPzFv9qEoOBGZfDr2nWBSDGi7DL0TOb
@api-url = http://localhost:4000/api/v1

### 1. Login - Get Access Token from Keycloak
# This request gets an access token that will be used for authenticated endpoints
# Run this first before any authenticated requests
POST {{keycloak-url}}/realms/{{keycloak-realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{client-id}}&client_secret={{client-secret}}&username={{test-username2}}&password={{test-password}}
> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
    client.log("✅ Token refreshed successfully!");
%}

### Create new Recipie
# Run the login request first, then run this
POST {{api-url}}/recipes
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Pizza Capri",
  "description": "Classic Italian pasta with meat sauce",
  "ingredients": [
    {
      "name": "Spaghetti",
      "quantity": 200,
      "unit": "GRAMS"
    },
    {
      "name": "Ground Beef",
      "quantity": 300,
      "unit": "GRAMS"
    },
    {
      "name": "Tomato Sauce",
      "quantity": 150,
      "unit": "MILLILITERS"
    }
  ],
  "instructions": [
    "Boil the spaghetti according to package instructions.",
    "Cook the beef until browned.",
    "Add tomato sauce and simmer for 10 minutes.",
    "Mix with spaghetti and serve."
  ],
  "preparationTime": "PT30M",
  "servings": 2,
  "dishType": "MAIN_DISH",
  "dietaryInformation": "NONE",
  "status": "PUBLISHED"
}

### Update existing Recipe
# Run the login request first, then run this
PUT {{api-url}}/recipes/881a98d4-c0f7-4996-8d42-3982a3f826c4
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": "881a98d4-c0f7-4996-8d42-3982a3f826c4",
  "name": "Spaghetti Bolognese updated",
  "description": "Classic Italian pasta with meat sauce",
  "ingredients": [
    {
      "id": "9f7077ac-689b-4e8c-abfa-840c9945ad52",
      "name": "Spaghetti updated",
      "quantity": 200.0,
      "unit": "GRAMS",
      "createdAt": "2025-08-12T14:38:37.470493",
      "updatedAt": "2025-08-12T14:38:37.470493"
    },
    {
      "id": "9b0b7770-1402-4ff1-a353-1fdc68623f48",
      "name": "Ground Beef",
      "quantity": 300.0,
      "unit": "GRAMS",
      "createdAt": "2025-08-12T14:38:37.470586",
      "updatedAt": "2025-08-12T14:38:37.470586"
    },
    {
      "id": "eb1eea24-32ee-4ceb-9bf1-8b15a9415f8a",
      "name": "Tomato Sauce",
      "quantity": 150.0,
      "unit": "MILLILITERS",
      "createdAt": "2025-08-12T14:38:37.470659",
      "updatedAt": "2025-08-12T14:38:37.470659"
    }
  ],
  "instructions": [
    "Boil the spaghetti according to package instructions.",
    "Cook the beef until browned.",
    "Add tomato sauce and simmer for 10 minutes.",
    "Mix with spaghetti and serve."
  ],
  "preparationTime": "PT30M",
  "servings": 2,
  "dishType": "MAIN_DISH",
  "dietaryInformation": "NONE",
  "status": "PUBLISHED",
  "createdAt": "2025-08-12T14:38:37.469536",
  "updatedAt": "2025-08-12T14:38:37.469536"
}

### Get single Recipe
GET {{api-url}}/recipes/1323a4ee-533a-49ba-860e-57439aead478

### Get all published recepies (summary)
GET {{api-url}}/recipes

### Get all published recepies that mech the search param
GET {{api-url}}/recipes?search=pizza

### Get all published recepies for a single user (summary)
GET {{api-url}}/recipes/user/66c8f446-8cdf-4c9b-a566-3e16175399fc

### Get all recepies for a single user (summary)
# Run the login request first, then run this
GET {{api-url}}/recipes/my-recipes
Authorization: Bearer {{auth_token}}

### Write a comment to a recipe
# Run the login request first, then run this
POST {{api-url}}/recipes/1323a4ee-533a-49ba-860e-57439aead478/comments
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "content": "Good recipe indeed"
}